trigger:
  branches:
    include:     
      - main

pool:
  name: Default

stages:
- stage: Build
  displayName: 'Build and Push Artifacts'
  jobs:
  - job: CI
    displayName: 'Continuous Integration'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - task: NuGetAuthenticate@0
      displayName: 'NuGet Authenticate'

    - script: dotnet restore --source https://pkgs.dev.azure.com/keerthana5y/Demo/_packaging/test/nuget/v3/index.json
      displayName: 'Restore dependencies'
      continueOnError: false

    - script: dotnet build --configuration Release
      displayName: 'Build application'
      continueOnError: false

    - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
      displayName: 'Publish Application'
      continueOnError: false

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact to Azure Artifacts'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        feed: 'test'
