trigger:
  branches:
    include:     
      - main

pool:
  name: Default

stages:
- stage: Build
  displayName: 'Build and Push Artifacts'
  jobs:
  - job: CI
    displayName: 'Continuous Integration'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - task: NuGetAuthenticate@0
      displayName: 'NuGet Authenticate'

    - script: |
        dotnet nuget add source https://pkgs.dev.azure.com/keerthana5y/Demo/_packaging/test/nuget/v3/index.json -n AzureArtifacts -u $(System.AccessToken) --store-password-in-clear-text
        dotnet restore
      displayName: 'Add NuGet Source and Restore dependencies'
      env:
        VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: '{"endpointCredentials": [{"endpoint": "https://pkgs.dev.azure.com/keerthana5y/Demo/_packaging/test/nuget/v3/index.json", "username": "", "password": "$(System.AccessToken)"}]}'

    - script: dotnet build --configuration Release
      displayName: 'Build application'

    - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
      displayName: 'Publish Application'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact to Azure Artifacts'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        feed: 'test'
