trigger:
  branches:
    include:     
      - main  

pool:
  name: Default

stages:
- stage: Build
  displayName: 'Build, Test and Publish Artifact'
  jobs:
  - job: CI
    displayName: 'Continuous Integration'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core sdk'
      inputs:
        packageType: 'sdk'
        version: '8.x'  

    - script: dotnet restore
      displayName: 'Restore dependencies'

    - script: dotnet build --configuration Release
      displayName: 'Build application'

    - script: dotnet test
      displayName: 'Run tests'

    - task: DotNetCoreCLI@2
      displayName: 'Publish Artifact'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
        modifyOutputPath: true
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: Container

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  jobs:
  - job: CD
    displayName: 'Continuous Deployment'
    steps:
    # - task: UseDotNet@2
    #   displayName: 'Install .NET Core sdk'
    #   inputs:
    #     packageType: 'sdk'
    #     version: '8.x'  

    # - task: DotNetCoreCLI@2
    #   displayName: 'Publish to Azure Web App'
    #   inputs:
    #     command: 'publish'
    #     publishWebProjects: true
    #     arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    #     zipAfterPublish: true

    - task: AzureRmWebAppDeployment@4
      displayName: 'Azure Web App Deploy'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure_DevOps_Service_Connection'
        appType: 'webApp'
        WebAppName: 'webapp-apitest-cc-fusionapi-001'
        packageForLinux: '$(Pipeline.Workspace)/drop/**/*.zip'
        enableCustomDeployment: true
        DeploymentType: 'zipDeploy'
        #deploymentMethod: 'zipDeploy'
        
    

























# # ASP.NET Core (.NET Framework)
# # Build and test ASP.NET Core projects targeting the full .NET Framework.
# # Add steps that publish symbols, save build artifacts, and more:
# # https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# trigger:
# - master

# pool:
#   vmImage: 'windows-latest'

# variables:
#   solution: '**/*.sln'
#   buildPlatform: 'Any CPU'
#   buildConfiguration: 'Release'

# steps:
# - task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'

# - task: VSBuild@1
#   inputs:
#     solution: '$(solution)'
#     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

# - task: VSTest@2
#   inputs:
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'