trigger:
  branches:
    include:     
      - main

pool:
  name: Default

stages:
- stage: Build
  displayName: 'Build and Push Artifacts'
  jobs:
  - job: CI
    displayName: 'Continuous Integration'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK'
      inputs:
        packageType: 'sdk'
        version: '8.x'  

    - script: dotnet restore
      displayName: 'Restore dependencies'

    - script: dotnet build --configuration Release
      displayName: 'Build application'

    - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
      displayName: 'Publish Application'
    
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact to Azure Artifacts'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'drop'
        feed: 'test'
