trigger:
  branches:
    include:
      - main  # You can add other branches here if needed

pool:
  name: Default

stages:
- stage: Build
  displayName: 'Build and Publish Artifact'
  jobs:
  - job: CI
    displayName: 'Continuous Integration'
    steps:
    - task: UseDotNet@2
      displayName: 'Install .NET Core sdk'
      inputs:
        packageType: 'sdk'
        version: '8.x'

    - script: dotnet restore
      displayName: 'Restore dependencies'

    - script: dotnet build --configuration Release
      displayName: 'Build application'

    - script: dotnet publish --configuration Release --output $(Build.ArtifactStagingDirectory)
      displayName: 'Publish Application'

    - task: PublishBuildArtifacts@1  # Update the task name if needed
      displayName: 'Publish Build Artifacts to Test Feed'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: Container
        feedName: 'test' # Add your test feed name here
